### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by MaximKsh** [MaximKsh/DeliveryTrackerAndroid#19]
- [x] фрагмент заползает под навбар
- [x] дергается дропдаун при первом нажатии
- [x] список дропдауна не от текущего списка при переключении с другого фрагмента
- [x] просмотр способа оплаты по клику и страница просмотра
- [x] просмотр клиента  по клику и страница просмотра
- [x] просмотр товара по клику и страница просмотра
- [x] просмотр склада по клику и страница просмотра
- [x] просмотр юзера по клику и страница просмотра
- [x] тулбар как отдельный компонент, грамотно продуманный и с настройками
- [x] строка поиска в дропдауне и кнопка обновления дайджеста дропдауна (скрываемые) 
- [x] валидация на поля
- [x] отображение ошибок от бэка

**Comment by avinograd0v** [comment]
Закрываем
