### ISSUE TITLE
TODO Защита

### ISSUE THREAD

**Issue by avinograd0v** [MaximKsh/DeliveryTrackerAndroid#37]
**До 15.05**
- [x] Фикс багов!!!
- [x] Локализация на русский
- [x] Простенькая статистика для курьеров/менеджеров
- [x] Стритвью дома доставки, карту в таске в статичную
- [ ] Простенький маршрутный лист для курьера с отображением координат, доступен менеджеру
- [ ] ?? Карта со всеми курьерами
